extern crate swimmer_rust;

#[test]fn rv64ui_p_add    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-add.bin"     .to_string()), 1); }
#[test]fn rv64ui_p_addi   () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-addi.bin"    .to_string()), 1); }
#[test]fn rv64ui_p_addiw  () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-addiw.bin"   .to_string()), 1); }
#[test]fn rv64ui_p_addw   () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-addw.bin"    .to_string()), 1); }
#[test]fn rv64ui_p_and    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-and.bin"     .to_string()), 1); }
#[test]fn rv64ui_p_andi   () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-andi.bin"    .to_string()), 1); }
#[test]fn rv64ui_p_auipc  () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-auipc.bin"   .to_string()), 1); }
#[test]fn rv64ui_p_beq    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-beq.bin"     .to_string()), 1); }
#[test]fn rv64ui_p_bge    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-bge.bin"     .to_string()), 1); }
#[test]fn rv64ui_p_bgeu   () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-bgeu.bin"    .to_string()), 1); }
#[test]fn rv64ui_p_blt    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-blt.bin"     .to_string()), 1); }
#[test]fn rv64ui_p_bltu   () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-bltu.bin"    .to_string()), 1); }
#[test]fn rv64ui_p_bne    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-bne.bin"     .to_string()), 1); }
#[test]fn rv64ui_p_fence_i() { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-fence_i.bin" .to_string()), 1); }
#[test]fn rv64ui_p_jal    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-jal.bin"     .to_string()), 1); }
#[test]fn rv64ui_p_jalr   () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-jalr.bin"    .to_string()), 1); }
#[test]fn rv64ui_p_lb     () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-lb.bin"      .to_string()), 1); }
#[test]fn rv64ui_p_lbu    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-lbu.bin"     .to_string()), 1); }
#[test]fn rv64ui_p_ld     () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-ld.bin"      .to_string()), 1); }
#[test]fn rv64ui_p_lh     () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-lh.bin"      .to_string()), 1); }
#[test]fn rv64ui_p_lhu    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-lhu.bin"     .to_string()), 1); }
#[test]fn rv64ui_p_lui    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-lui.bin"     .to_string()), 1); }
#[test]fn rv64ui_p_lw     () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-lw.bin"      .to_string()), 1); }
#[test]fn rv64ui_p_lwu    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-lwu.bin"     .to_string()), 1); }
#[test]fn rv64ui_p_or     () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-or.bin"      .to_string()), 1); }
#[test]fn rv64ui_p_ori    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-ori.bin"     .to_string()), 1); }
#[test]fn rv64ui_p_sb     () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-sb.bin"      .to_string()), 1); }
#[test]fn rv64ui_p_sd     () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-sd.bin"      .to_string()), 1); }
#[test]fn rv64ui_p_sh     () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-sh.bin"      .to_string()), 1); }
#[test]fn rv64ui_p_simple () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-simple.bin"  .to_string()), 1); }
#[test]fn rv64ui_p_sll    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-sll.bin"     .to_string()), 1); }
#[test]fn rv64ui_p_slli   () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-slli.bin"    .to_string()), 1); }
#[test]fn rv64ui_p_slliw  () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-slliw.bin"   .to_string()), 1); }
#[test]fn rv64ui_p_sllw   () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-sllw.bin"    .to_string()), 1); }
#[test]fn rv64ui_p_slt    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-slt.bin"     .to_string()), 1); }
#[test]fn rv64ui_p_slti   () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-slti.bin"    .to_string()), 1); }
#[test]fn rv64ui_p_sltiu  () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-sltiu.bin"   .to_string()), 1); }
#[test]fn rv64ui_p_sltu   () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-sltu.bin"    .to_string()), 1); }
#[test]fn rv64ui_p_sra    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-sra.bin"     .to_string()), 1); }
#[test]fn rv64ui_p_srai   () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-srai.bin"    .to_string()), 1); }
#[test]fn rv64ui_p_sraiw  () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-sraiw.bin"   .to_string()), 1); }
#[test]fn rv64ui_p_sraw   () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-sraw.bin"    .to_string()), 1); }
#[test]fn rv64ui_p_srl    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-srl.bin"     .to_string()), 1); }
#[test]fn rv64ui_p_srli   () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-srli.bin"    .to_string()), 1); }
#[test]fn rv64ui_p_srliw  () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-srliw.bin"   .to_string()), 1); }
#[test]fn rv64ui_p_srlw   () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-srlw.bin"    .to_string()), 1); }
#[test]fn rv64ui_p_sub    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-sub.bin"     .to_string()), 1); }
#[test]fn rv64ui_p_subw   () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-subw.bin"    .to_string()), 1); }
#[test]fn rv64ui_p_sw     () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-sw.bin"      .to_string()), 1); }
#[test]fn rv64ui_p_xor    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-xor.bin"     .to_string()), 1); }
#[test]fn rv64ui_p_xori   () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-p-xori.bin"    .to_string()), 1); }

#[test]fn rv64ui_p_div    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64um-p-div.bin"    .to_string()), 1); }
#[test]fn rv64ui_p_divu   () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64um-p-divu.bin"   .to_string()), 1); }
#[test]fn rv64ui_p_divuw  () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64um-p-divuw.bin"  .to_string()), 1); }
#[test]fn rv64ui_p_divw   () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64um-p-divw.bin"   .to_string()), 1); }
#[test]fn rv64ui_p_mul    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64um-p-mul.bin"    .to_string()), 1); }
#[test]fn rv64ui_p_mulh   () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64um-p-mulh.bin"   .to_string()), 1); }
#[test]fn rv64ui_p_mulhsu () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64um-p-mulhsu.bin" .to_string()), 1); }
#[test]fn rv64ui_p_mulhu  () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64um-p-mulhu.bin"  .to_string()), 1); }
#[test]fn rv64ui_p_mulw   () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64um-p-mulw.bin"   .to_string()), 1); }
#[test]fn rv64ui_p_rem    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64um-p-rem.bin"    .to_string()), 1); }
#[test]fn rv64ui_p_remu   () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64um-p-remu.bin"   .to_string()), 1); }
#[test]fn rv64ui_p_remuw  () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64um-p-remuw.bin"  .to_string()), 1); }
#[test]fn rv64ui_p_remw   () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64um-p-remw.bin"   .to_string()), 1); }


#[test]fn rv64ui_v_add     () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-add.bin"     .to_string()), 1); }
#[test]fn rv64ui_v_addi    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-addi.bin"    .to_string()), 1); }
#[test]fn rv64ui_v_addiw   () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-addiw.bin"   .to_string()), 1); }
#[test]fn rv64ui_v_addw    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-addw.bin"    .to_string()), 1); }
#[test]fn rv64ui_v_and     () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-and.bin"     .to_string()), 1); }
#[test]fn rv64ui_v_andi    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-andi.bin"    .to_string()), 1); }
#[test]fn rv64ui_v_auipc   () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-auipc.bin"   .to_string()), 1); }
#[test]fn rv64ui_v_beq     () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-beq.bin"     .to_string()), 1); }
#[test]fn rv64ui_v_bge     () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-bge.bin"     .to_string()), 1); }
#[test]fn rv64ui_v_bgeu    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-bgeu.bin"    .to_string()), 1); }
#[test]fn rv64ui_v_blt     () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-blt.bin"     .to_string()), 1); }
#[test]fn rv64ui_v_bltu    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-bltu.bin"    .to_string()), 1); }
#[test]fn rv64ui_v_bne     () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-bne.bin"     .to_string()), 1); }
#[test]fn rv64ui_v_fence_i () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-fence_i.bin" .to_string()), 1); }
#[test]fn rv64ui_v_jal     () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-jal.bin"     .to_string()), 1); }
#[test]fn rv64ui_v_jalr    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-jalr.bin"    .to_string()), 1); }
#[test]fn rv64ui_v_lb      () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-lb.bin"      .to_string()), 1); }
#[test]fn rv64ui_v_lbu     () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-lbu.bin"     .to_string()), 1); }
#[test]fn rv64ui_v_ld      () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-ld.bin"      .to_string()), 1); }
#[test]fn rv64ui_v_lh      () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-lh.bin"      .to_string()), 1); }
#[test]fn rv64ui_v_lhu     () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-lhu.bin"     .to_string()), 1); }
#[test]fn rv64ui_v_lui     () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-lui.bin"     .to_string()), 1); }
#[test]fn rv64ui_v_lw      () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-lw.bin"      .to_string()), 1); }
#[test]fn rv64ui_v_lwu     () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-lwu.bin"     .to_string()), 1); }
#[test]fn rv64ui_v_or      () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-or.bin"      .to_string()), 1); }
#[test]fn rv64ui_v_ori     () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-ori.bin"     .to_string()), 1); }
#[test]fn rv64ui_v_sb      () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-sb.bin"      .to_string()), 1); }
#[test]fn rv64ui_v_sd      () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-sd.bin"      .to_string()), 1); }
#[test]fn rv64ui_v_sh      () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-sh.bin"      .to_string()), 1); }
#[test]fn rv64ui_v_simple  () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-simple.bin"  .to_string()), 1); }
#[test]fn rv64ui_v_sll     () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-sll.bin"     .to_string()), 1); }
#[test]fn rv64ui_v_slli    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-slli.bin"    .to_string()), 1); }
#[test]fn rv64ui_v_slliw   () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-slliw.bin"   .to_string()), 1); }
#[test]fn rv64ui_v_sllw    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-sllw.bin"    .to_string()), 1); }
#[test]fn rv64ui_v_slt     () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-slt.bin"     .to_string()), 1); }
#[test]fn rv64ui_v_slti    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-slti.bin"    .to_string()), 1); }
#[test]fn rv64ui_v_sltiu   () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-sltiu.bin"   .to_string()), 1); }
#[test]fn rv64ui_v_sltu    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-sltu.bin"    .to_string()), 1); }
#[test]fn rv64ui_v_sra     () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-sra.bin"     .to_string()), 1); }
#[test]fn rv64ui_v_srai    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-srai.bin"    .to_string()), 1); }
#[test]fn rv64ui_v_sraiw   () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-sraiw.bin"   .to_string()), 1); }
#[test]fn rv64ui_v_sraw    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-sraw.bin"    .to_string()), 1); }
#[test]fn rv64ui_v_srl     () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-srl.bin"     .to_string()), 1); }
#[test]fn rv64ui_v_srli    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-srli.bin"    .to_string()), 1); }
#[test]fn rv64ui_v_srliw   () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-srliw.bin"   .to_string()), 1); }
#[test]fn rv64ui_v_srlw    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-srlw.bin"    .to_string()), 1); }
#[test]fn rv64ui_v_sub     () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-sub.bin"     .to_string()), 1); }
#[test]fn rv64ui_v_subw    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-subw.bin"    .to_string()), 1); }
#[test]fn rv64ui_v_sw      () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-sw.bin"      .to_string()), 1); }
#[test]fn rv64ui_v_xor     () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-xor.bin"     .to_string()), 1); }
#[test]fn rv64ui_v_xori    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64ui-v-xori.bin"    .to_string()), 1); }

#[test]fn rv64um_v_div     () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64um-v-div.bin"     .to_string()), 1); }
#[test]fn rv64um_v_divu    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64um-v-divu.bin"    .to_string()), 1); }
#[test]fn rv64um_v_divuw   () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64um-v-divuw.bin"   .to_string()), 1); }
#[test]fn rv64um_v_divw    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64um-v-divw.bin"    .to_string()), 1); }
#[test]fn rv64um_v_mul     () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64um-v-mul.bin"     .to_string()), 1); }
#[test]fn rv64um_v_mulh    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64um-v-mulh.bin"    .to_string()), 1); }
#[test]fn rv64um_v_mulhsu  () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64um-v-mulhsu.bin"  .to_string()), 1); }
#[test]fn rv64um_v_mulhu   () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64um-v-mulhu.bin"   .to_string()), 1); }
#[test]fn rv64um_v_mulw    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64um-v-mulw.bin"    .to_string()), 1); }
#[test]fn rv64um_v_rem     () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64um-v-rem.bin"     .to_string()), 1); }
#[test]fn rv64um_v_remu    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64um-v-remu.bin"    .to_string()), 1); }
#[test]fn rv64um_v_remuw   () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64um-v-remuw.bin"   .to_string()), 1); }
#[test]fn rv64um_v_remw    () { assert_eq!(swimmer_rust::swimmer_rust_exec("riscv-tests/isa/rv64um-v-remw.bin"    .to_string()), 1); }
